name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: TerraDharitri/drt-sc-actions/.github/workflows/contracts.yml@v0.0.1
    with:
      rust-toolchain: stable
      drt-go-scenario-verison: v0.0.2-4
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
